# yamlfix configuration
# Configuration options for yamlfix
# @docs: <https://lyz-code.github.io/yamlfix/>
# This file should be in the root directory of the project

line_length = 110

# Force sequences to use block style (multi-line lists)
sequence_style = "block_style"
